# copy envvars from heroku, rename
export MAILROOM_DB=${DATABASE_URL}
export MAILROOM_REDIS=${REDIS_URL}/0
export MAILROOM_PORT=${PORT}
export MAILROOM_LIBRATO_USERNAME=${LIBRATO_USER}
export MAILROOM_LIBRATO_TOKEN=${LIBRATO_TOKEN}